column_title_dict = {
    "electro":
        {
            "Oxygen Reduction Reaction":
                {
                    "Formula": "e.g. PtNi",
                    "Type": "",
                    "Elements": "e.g. Pt,Ni",
                    "Content": "e.g. Pt/Ni=60.7/39.3",
                    "Structural Property": "e.g. [PtNi(111)] or [Co site on Co-porphyrin-N surface]",
                    "Electrolytes": "e.g. 0.1 M HClO4",
                    "pH": "e.g. 0~14",
                    "Rotation_Speed (rpm)": "e.g. 1600",
                    "Half-wave Potential (V/RHE)": "e.g. 0.90",
                    "On-set potential, disk electrode (V/RHE@j mA cm-2)": "e.g. 0.95@0.5",
                    "On-set potential, ring electrode (V/RHE@j mA cm-2)": "e.g. 0.65@0.1",
                    "Disk total current density (mAcm-2@V/RHE)": "e.g. 3.0@0.9",
                    "Disk total TOF (s-1@V/RHE)": "e.g. 1.0@0.9",
                    "Disk ring current density (mAcm-2@V/RHE)": "e.g. 0.1@0.6",
                    "Disk ring TOF (s-1@V/RHE)": "e.g. 1.0@0.6",
                    "H2O2 faradaic Efficiency (%@V/RHE)": "e.g. 80%@0.6",
                    "ECSA(HUPD (m2 g-1)": "e.g. 43.5",
                    "Mass Activity (A mg-1@V/RHE)": "e.g. 1.89@0.9",
                    "Specific Acticity (mA cm-2@V/RHE)": "e.g. 4.34@0.9",
                    "Stability Test (h@V/RHE)": "e.g. 30000@0.6",
                    "Durability Loss %(Performace metrics)": "e.g. 13.7%(MA)",
                    "Structural change after tests": "Describe the structure or content change after durability tests",
                    "Year": "e.g. 2019"
                },
            "Oxygen Evolution Reaction":
                {
                    "Formula": "e.g. RuCu",
                    "Type": "",
                    "Elements": "e.g. Ru,Cu",
                    "Content": "Ru/Cu=5.5/1",
                    "Structural Property": "e.g. Nanosheet-Ru(100)",
                    "Catalyst loading on electrode (mg cm-2)": "e.g. 1.1",
                    "Working electrode": "e.g. glassy carbon electrode",
                    "Electrolytes": "e.g. 1 M KOH",
                    "pH": "e.g. 13.6",
                    "Over_Potential (mV@ j mA cm-2)": "e.g. 234@10",
                    "Current_density (mA/cm2@ U V/RHE)": "e.g. 40@1.79",
                    "Tafel_slope (mVdev-1)": "e.g. 80",
                    "Device test": "Please enter yes/no",
                    "Stability Test (h@ mAcm-2)": "e.g. 45@5",
                    "Durability Loss %(performace metrics)": "e.g. 5%(Current_density)",
                    "Year": "e.g. 2019",
                },
            "Hydrogen Evolution Reaction":
                {
                    "Formula": "e.g. RuCu",
                    "Type": "",
                    "Elements": "e.g. Ru,Cu",
                    "Content": "Ru/Cu=5.5/1",
                    "Structural Property": "e.g. Nanosheet-Ru(100)",
                    "Catalyst loading on electrode (mg cm-2)": "e.g. 1.1",
                    "Working electrode": "e.g. glassy carbon electrode",
                    "Electrolytes": "e.g. 1 M KOH",
                    "Over_Potential (mV@ j mA cm-2)": "e.g. 20@10",
                    "Tafel_slope (mVdev-1)": "e.g. 15.3",
                    "Device test": "Please enter yes/no",
                    "Stability Test (h@ mAcm-2)": "e.g. 45@5",
                    "Durability Loss %(performace metrics)": "e.g. 5%(Current_density)",
                    "Year": "e.g. 2019",
                },
            "Carbon Dioxide Reduction":
                {
                    "Formula": "e.g. Ni-Zn-N-C",
                    "Type": "",
                    "Elements": "e.g. Ni,Zn",
                    "Content": "e.g. Ni/Zn=0.84/1.32",
                    "Structural Property": "e.g. Zn-Ni-N6-C, Dual-atom M-N-C catalysts",
                    "Electrolytes": "0.5 M KHCO3",
                    "Temperature (Celsius)": "e.g. 60",
                    "pressure (bar)": "e.g. 1",
                    "Type of cell": "e.g. AEM flow cell",
                    "pH": "e.g. 6.8",
                    "Main product": "",
                    "Other product (FE > 10%)": "",
                    "Main product faradaic efficiency (%@U V/RHE)": "e.g. 99%@-0.73",
                    "Current density (mA cm-2@U V/RHE)": "e.g. 17.5@-0.8",
                    "Stability Test (h@ mAcm-2)": "e.g. 28@14",
                    "Durability Loss %(performace metrics)": "e.g. 4%(faradaic efficiency)",
                    "Year": "e.g. 2021",
                },
            "Carbon Monoxide Reduction":
                {
                    "Formula": "e.g. Ni-Zn-N-C",
                    "Type": "",
                    "Elements": "e.g. Ni,Zn",
                    "Content": "e.g. Ni/Zn=0.84/1.32",
                    "Structural Property": "e.g. Zn-Ni-N6-C, Dual-atom M-N-C catalysts",
                    "Electrolytes": "0.5 M KHCO3",
                    "Temperature (Celsius)": "e.g. 60",
                    "pressure (bar)": "e.g. 1",
                    "Type of cell": "e.g. AEM flow cell",
                    "pH": "e.g. 6.8",
                    "Main product": "",
                    "Other product (FE > 10%)": "",
                    "Main product faradaic efficiency (%@U V/RHE)": "e.g. 99%@-0.73",
                    "Current density (mA cm-2@U V/RHE)": "e.g. 17.5@-0.8",
                    "Stability Test (h@ mAcm-2)": "e.g. 28@14",
                    "Durability Loss %(performace metrics)": "e.g. 4%(faradaic efficiency)",
                    "Year": "e.g. 2021",
                },
            "Ammonia Synthesis":
                {
                    "Formula": "e.g. Au/Ni",
                    "Type": "",
                    "Elements": "e.g. Au,Ni",
                    "Content": "e.g. Au/Ni=6/1",
                    "Structural Property": "e.g. Adjacent Au NPs and Ni NPs on Nitrogen-doped carbon",
                    "Isotope labeling": "",
                    "Electrolytes": "e.g. N2-saturated 0.05 M H2SO4",
                    "pH": "e.g. 1.0",
                    "Reactant": "",
                    "Quantification method": "e.g. spectrophotometer or NMR",
                    "faradaic Efficiency (%@U V/RHE)": "67.8%@-0.14",
                    "Current density (mA cm-2@U V/RHE)": "e.g. 17.5@-0.8",
                    "Rate (μg h-1 mg-1@U V/RHE)": "7.4@-0.14",
                    "Year": "e.g. 2019",
                },
            "Hydrogen Oxidation Reaction":
                {
                    "Formula": "e.g. 3%Pt-Ru/C",
                    "Type": "",
                    "Elements": "e.g. Pt,Ru",
                    "Content": "e.g. Pt/Ru=3/97",
                    "Structural Property": "e.g. Pt single atom in Ru-N-C structures",
                    "Electrolytes": "e.g. 0.1 M KOH",
                    "pH": "e.g. 13",
                    "Exchange current densities (mA cm-2 @ V/RHE)": "e.g. 4.16@0.05",
                    "Mass-normalized kinetic current density (mA cm-2 ug-1@U mV/RHE)": "1.71@50",
                    "Mass activity (A/mg @ V/RHE)": "e.g. 0.65@0.05",
                    "Stability Test (h@ mAcm-2)": "e.g. 100@1.71",
                    "Year": "e.g. 2024",
                },
            "Hydrogen Peroxide Synthesis":
                {
                    "Formula": "e.g. LaAlO3/FTO",
                    "Type": "",
                    "Elements": "e.g. La,Al",
                    "Content": "e.g. La/Al=9.6/9.1",
                    "Structural Property": "e.g. LaAlO3 (100）and (110）",
                    "Working electrode": "e.g. LaAlO3/FTO",
                    "Counter electrode": "e.g. Carbon rod",
                    "Reference electrode": "e.g. Ag/AgCl (KCl Sat.)",
                    "Electrolytes": "e.g. 4M K2CO3/ KHCO3",
                    "pH": "e.g. 8.3",
                    "Rotation_Speed (rpm)": "e.g. 1000",
                    "Over_Potential(mV@j mAcm-2)": "e.g. 510@10",
                    "On-set potential,three-electrode (V/RHE@j mA cm-2 )": "2.1@2",
                    "Total current density (mAcm-2@U V/RHE)": "e.g. 18.5@2.4",
                    "H2O2 current density (mAcm-2@U V/RHE)": "e.g. 34.2@3.2",
                    "H2O2 Measurement Method": "e.g. UV-vis and  titration",
                    "H2O2_peak faradaic_Efficiency (%@ U/RHE)": "e.g. 87@3.34",
                    "Maximum  H2O2 production rates（mmol cm-2 min-1)/ppm min-1 @ V/RHE": "e.g. 0.00089@2.7",
                    "ECSA(HUPD)(m2 g-1)": "e.g. 2.76",
                    "Stability Test (h@U V/RHE)": "e.g. 3@2.7",
                    "Durability Loss %(performace metrics)": "e.g. 3%(faradaic efficiency)",
                    "Year": "e.g. 2022",
                },
            "Epoxide Production":
                {
                    "Formula": "e.g. Pd3Pt1",
                    "Type": "",
                    "Elements": "e.g. Pd,Pt",
                    "Content": "e.g. Pd/Pt=3/1",
                    "Structural Property": "e.g. Pd3Pt1 (111)",
                    "Catalyst loading on electrode (mg cm-2)": "e.g. 0.5",
                    "Electrolytes": "e.g. 0.4 M TBABF4",
                    "pH": "e.g. 6",
                    "Halogen-Mediated": "yes/no",
                    "Current density (mAcm-2@U V/RHE)": "e.g. 18.5@2.4",
                    "Highest epoxide production rate (μmol/cm2/h)": "9.2",
                    "Epoxidation FE at the highest rate (%@V/RHE)": "61%",
                    "Main product": "",
                    "Year": "e.g. 2022",
                },
            "Chlorination Evolution Reaction":
                {
                    "Formula": "e.g. Pt1(3)/CNT",
                    "Type": "",
                    "Elements": "e.g. Pt",
                    "Content": "e.g. Pt=3",
                    "Structural Property": "e.g. Pd3Pt1 (111)",
                    "Electrolytes": "e.g. 0.1 M HClO4+1 M NaCl",
                    "pH": "e.g. 1.3",
                    "Over potential (mV@j mA cm-2)": "e.g. 50@10",
                    "Cl2 selectivity": "99.5",
                    "Year": "e.g. 2023",
                },
            "Ozone Evolution Reaction":
                {
                    "Formula": "e.g. PtNi",
                    "Type": "",
                    "Elements": "e.g. Pt,Ni,B",
                    "Content": "e.g. Pt/Ni/B=2.5/5.58/20.1",
                    "Structural Property": "e.g. B13C2‑Encapsulated PtNi Alloy Electrocatalyst (001) (110)",
                    "Electrolytes": "e.g. K2SO4",
                    "pH": "e.g. 7",
                    "On-set Potential (V/RHE@j mA cm-2)": "e.g. 2.54@10",
                    "Tafel_slope(mVdev-1)": "e.g. 184",
                    "faradaic Efficiency (%@j mAcm-2)": "e.g. 15%@50",
                    "other production": "e.g. H2O2",
                    "Selectivity for ozone (%@V/RHE)": "e.g. 40%",
                    "Selectivity for other production (%@V/RHE)": "e.g. 90%@0.6",
                    "Production rate (mg/L@j mA cm-2)": "e.g. 3.8@50",
                    "Stability Test (hour@U V/RHE)": "e.g. 120@2.8",
                    "Durability Loss %(performace metrics)": "e.g. 1%(Current_density)",
                    "Year": "e.g. 2023",

                },
            "Nitrogen Oxidation Reaction":
                {
                    "Formula": "e.g. Sr0.9RuO3",
                    "Type": "",
                    "Elements": "e.g. Sr,Ru,O",
                    "Content": "e.g. Sr/Ru/O=0.9/1/3",
                    "Structural Property": "e.g. Sr0.9RuO3(121)",
                    "Electrolytes": "e.g. N2-saturated 0.1 M Na2SO4",
                    "pH": "e.g. 7",
                    "Quantification method": "e.g. spectroscopy",
                    "Main product": "",
                    "faradaic Efficiency (%@U V/RHE)": "38.6@2.2",
                    "Rate (μg h-1 mg-1 @U V/RHE)": "17.9@2.2",
                    "Year": "e.g. 2024",
                },
            "NH3 Oxidation Reaction":
                {
                    "Formula": "e.g. CuCo/CC",
                    "Type": "",
                    "Elements": "e.g. Cu,Co",
                    "Content": "e.g. Cu/Co=1/2",
                    "Structural Property": "e.g.  self-supported CuM on carbon cloth",
                    "Electrolytes": "e.g. 0.5 M K2SO4",
                    "pH": "e.g. 11",
                    "initial NH3 concentration (mol/L)": "e.g. 0.1",
                    "Main product": "",
                    "faradaic Efficiency (%@U V/RHE)": "e.g. 90%@1.85",
                    "Temperature (Degrees Celsius)": "e.g. 25",
                    "Year": "e.g. 2023",
                },
            "Urea Oxidation Reaction":
                {
                    "Formula": "e.g. Ru-Co DAS/NiO",
                    "Type": "",
                    "Elements": "e.g. Ru,Co,Ni,O",
                    "Content": "e.g. Ru/Co=1/1",
                    "Structural Property": "e.g.  Ru-Co DAS/NiO heterostructure.NiO(222),(220),(200)",
                    "Electrolytes": "e.g. 0.1 M KOH",
                    "pH": "e.g. 13",
                    "Main product": "",
                    "faradaic efficiency (%@U V/RHE)": "e.g. 85%@1.288",
                    "Potential (V/RHE@j mAcm-2)": "e.g. 1.288@10",
                    "Stability (h@j mA cm-2)": "330@10",
                    "Year": "e.g. 2023",
                },
            "Hydrazine Oxidation Reaction":
                {
                    "Formula": "e.g. Ir-SA/NC",
                    "Type": "",
                    "Elements": "e.g. Ir",
                    "Content": "e.g. Ir=0.45",
                    "Structural Property": "e.g.  Iridium Single Atoms",
                    "Electrolytes": "e.g. 0.5 M H2SO4",
                    "pH": "e.g. 1.3",
                    "Main product": "e.g. N2",
                    "Over Potential (mV@j mA cm-2)": "e.g. 390@10",
                    "Tafel slope (mV dec-1)": "e.g. 78",
                    "Stability (h@j mA cm-2)": "e.g. 100@100",
                    "Year": "e.g. 2023",
                },
            "Urea Synthesis":
                {
                    "Formula": "e.g. In(OH)3-S",
                    "Type": "",
                    "Elements": "e.g. In",
                    "Content": "e.g. In/O/H=1/3/3",
                    "Structural Property": "e.g.  In(OH)3 (100)",
                    "Electrolytes": "e.g. 0.1M KNO3+0.05 KHCO3",
                    "pH": "e.g. 6.8",
                    "faradaic efficiency (%@U V/RHE)": "e.g. 53.4@-0.6",
                    "Rate (μg h-1 mg-1 )": "e.g. 533.1",
                    "Stability (h@U V/RHE)": "12@-0.6",
                    "Year": "e.g. 2023",
                },
            "Nitrate Reduction":
                {
                    "Formula": "e.g. PdCu/C",
                    "Type": "",
                    "Elements": "e.g. Pd,Cu",
                    "Content": "e.g. Pd/Cu=1/9",
                    "Structural Property": "e.g.  bimetallic nanoparticles on graphene",
                    "Electrolytes": "e.g. 0.2 M KOH + 0.1 M KNO3",
                    "pH": "e.g. 13",
                    "Current density (mA cm-2@U V/RHE)": "e.g. 5@-0.35",
                    "faradaic efficiency (%@U V/RHE)": "e.g. 53.4",
                    "Main product": "e.g. N2",
                    "Rate (mmol min−1 gcat−1@U V/RHE)": "0.66@0.26",
                    "Year": "e.g. 2023",
                },
            "Electrocatalytic hydrogenation":
                {
                    "Formula": "e.g. Cu/C",
                    "Type": "",
                    "Elements": "e.g. Cu,C",
                    "Content": "e.g. Cu/C=9.6/90.4",
                    "Structural Property": "e.g. Cu/C composite",
                    "Electrolytes": "e.g. 0.5 M solution of Na2SO4",
                    "pH": "e.g. 13",
                    "Turnover frequencies (min-1 @U V/RHE)": "0.22@-1.5",
                    "faradaic efficiency (%@U V/RHE)": "e.g. 3.5@-1.5",
                    "Reactant": "e.g. hydroxyacetone",
                    "Main product": "e.g. propylene glycol",
                    "Year": "e.g. 2016",
                },
            "CH4 Oxidation Reaction":
                {
                    "Formula": "e.g. Ru-NiO/V2O5",
                    "Type": "",
                    "Elements": "e.g. V,Ni,Rh",
                    "Content": "e.g. V/Ni=10.20/3.90",
                    "Structural Property": "e.g. Rh single atoms, dispersed in NiO and V2O5",
                    "Electrolytes": "e.g. 0.5 M Na2CO3",
                    "pH": "e.g. 12",
                    "Product": "e.g. CH3OH or CH3CH2OH",
                    "faradaic efficiency (%@U V/RHE)": "e.g. 81%@1.5",
                    "Rate (mol h−1 g−1)": "e.g. 0.65",
                    "Year": "e.g. 2023",
                },
            "Methanol Ethanol Reforming": {
                "Formula": "e.g. Pd/C",
                "Type": "",
                "Elements": "e.g. Pd,C",
                "Content": "e.g. Pd=20",
                "Structural Property": "e.g. Pd/C",
                "Electrolytes": "e.g. 4 M KOH",
                "pH": "e.g. 13.6",
                "Reactant": "e.g. CH3CH2OH or CH3OH",
                "Product": "e.g. H2 or acetate or formate",
                "faradaic efficiency (%@U V/RHE)": "e.g. 100%@1.4",
                "Rate (mmol cm-2 h-1@U V/RHE)": "0.34@1.4",
                "Year": "e.g. 2020",
            },
            "Organic Electrocatalysis":
                {
                    "Formula": "e.g. Fe–N–C-700",
                    "Type": "",
                    "Elements": "e.g. Fe",
                    "Content": "e.g. Fe=1.71",
                    "Structural Property": "e.g. Fe-pyridine/pyrrole-N M-N-C catalysts",
                    "Electrolytes": "e.g. 0.5 M OA + 0.5 M NaNO3",
                    "pH": "e.g. 1.3",
                    "Reaction Type": "e.g. Hydrodechlorination",
                    "Reactant": "e.g. Oxalic acid and NO3–/NOx",
                    "Production": "e.g. glycine",
                    "Current density (mA cm-2@ V/RHE)": "e.g. 10@1.5",
                    "faradaic efficiency (%@U V/RHE)": "e.g. 64.2%@-0.9",
                    "Mass Activity (mA mg-l@V/RHE)": "e.g. 50@-0.9",
                    "ECSA(HUPD (m2 g-1)": "e.g. 0.25",
                    "Specific Acticity(mA cm-2@V/RHE)": "4.34@0.9",
                    "Durability Loss %(Performace metrics)": "13.7%(MA)",
                    "Stability (h@U V/RHE)": "12@-0.9",
                    "Year": "e.g. 2020",
                },
            "CO Oxidation Reaction":
                {
                    "Formula": "e.g. Ru-NiO/V2O5",
                    "Type": "",
                    "Elements": "e.g. V,Ni,Rh",
                    "Content": "e.g. V/Ni=10.20/3.90",
                    "Structural Property": "e.g. Rh single atoms, dispersed in NiO and V2O5",
                    "Electrolytes": "e.g. 0.5 M Na2CO3",
                    "pH": "e.g. 12",
                    "Product": "e.g. CH3OH or CH3CH2OH",
                    "Onset potential (V/RHE@ mAcm-2)": "e.g. 0.03@10",
                    "Current density (mAcm-2@V/RHE)": "e.g. 50@0.4",
                    "faradaic efficiency (%@U V/RHE)": "e.g. 81%@1.5",
                    "Rate (mol h−1 g−1)": "e.g. 0.65",
                    "Year": "e.g. 2023",
                },
            "HMF oxidation":
                {
                    "Formula": "e.g. Ru@NixCo1−x(OH)2",
                    "Type": "",
                    "Elements": "e.g. Ru,Ni,Co",
                    "Content": "e.g. Ru=0.06 mmol or Ru/Ni/Co=0.1/1/1",
                    "Structural Property": "e.g. Ru nanoparticles on (011) plane of Ni(OH)2 and Co(OH)2",
                    "Electrolytes": "e.g. 1 M KOH",
                    "pH": "e.g. 13",
                    "Product": "e.g. 2,5-furandicarboxylic acid (FDCA)",
                    "faradaic efficiency (%@U V/RHE)": "e.g. 99%@1.45",
                    "On-set potential (V/RHE@j mA cm-2)": "e.g. 1.45@10",
                    "Stability (cycles@U V/RHE)": "e.g. 6@1.40",
                    "Year": "e.g. 2023",
                },
            "Acetylene semihydrogenation":
                {
                    "Formula": "e.g. Cu NDs",
                    "Type": "",
                    "Elements": "e.g. Cu,C",
                    "Content": "e.g. Cu/C=29/71 at.%",
                    "Structural Property": "e.g. an average size of 4.4 ± 0.6 nm Cu nanodots, (111) plane",
                    "Electrolytes": "e.g. 1 M KOH",
                    "pH": "e.g. 13",
                    "Main product": "e.g. C2H4",
                    "faradaic efficiency (%@U V/RHE)": "e.g. 95.9%@-0.69",
                    "Current density (mA cm-2@U V/RHE)": "e.g. -452@-0.79",
                    "Year": "e.g. 2023",
                },
            "Ammoximation Reaction":
                {
                    "Formula": "e.g. Cu NDs",
                    "Type": "",
                    "Elements": "e.g. Cu,C",
                    "Content": "e.g. Cu/C=29/71 at.%",
                    "Structural Property": "e.g. an average size of 4.4 ± 0.6 nm Cu nanodots, (111) plane",
                    "Electrolytes": "e.g. 1 M KOH",
                    "pH": "e.g. 13",
                    "Main product": "e.g. C2H4",
                    "faradaic efficiency (%@U V/RHE)": "e.g. 95.9%@-0.69",
                    "Current density (mA cm-2@U V/RHE)": "e.g. -452@-0.79",
                    "Yield rate (mmol/(h^-1 g^-1) @ U/RHE)": "e.g. 20@0.1",
                    "Stability test (h@ mA)": "e.g. 50@60",
                    "Year": "e.g. 2023",
                },
            "Oxygen-containing radical": {
                "Formula": "e.g. TiO2/C",
                "Type": "",
                "Elements": "e.g. Ti,C",
                "Content": "e.g. Ti/C=60/40 at.%",
                "Structural Property": "e.g. TiO2/C modified glassy carbon",
                "Electrolytes": "e.g. 0.05 M Na2SO4",
                "pH": "e.g. 6.8",
                "Product radicals": "e.g. HO*",
                "faradaic efficiency (%@U V/RHE)": "e.g. 95.9%@-0.69",
                "Production rate (ug min-1 cm-2)": "e.g. 2.69",
                "Current density (mA cm-2@ V/RHE)": "e.g. -0.3@-0.7",
                "Stability (h@mA cm-2)": "e.g. 100@0.1",
                "Year": "e.g. 2020",
            }
            ,
        },
    "thermo": {
        # thermo catalysis
        "Propane dehydrogenation":
            {
                "Formula": "e.g. ZnOx",
                "Type": "",
                "Elements": "e.g. Zn,O",
                "Content": "e.g.Zn/O:1/1",
                "Structural Property": "e.g. a physical mixture of ZnO (8wt%) and non-acidic SiO2 material",
                "Temperature(Celsius)": "e.g. 550",
                "Pressure (bar)": "1.2",
                "Reactant": "e.g. C3H8:H2:N2=4:2:4",
                "rate (mmol-1 g-1 min-1)": "e.g. 1.7",
                "Conversion degree (%)": "e.g. 10%",
                "TOF (h-1)": "e.g. 239",
                "Selectivity (%)": "e.g. 91.9",
                "Stability (h)": "e.g. 400",
                "Year": "e.g. 2021"
            },
        "Carbon monoxide oxidation":
            {
                "Formula": "e.g. ZnOx",
                "Type": "",
                "Elements": "e.g. Zn,O",
                "Content": "e.g. Zn/O:1/1",
                "Structural Property": "e.g. a physical mixture of ZnO (8wt%) and non-acidic SiO2 material",
                "Temperature(Celsius@conversion 10%)": "e.g. 550",
                "Temperature(Celsius)": "e.g. 550",
                "Pressure (bar)": "1.2",
                "Reactant": "e.g. CO:O2=2:1",
                "rate (mol g-1 h-1)": "e.g. 1.7",
                "Conversion degree (%)": "e.g. 10%",
                "TOF (s-1)": "e.g. 2.5",
                "Apparent activation energy Ea (kJ/mol)": "e.g. 2.4",
                "Selectivity (%)": "e.g. 91.9",
                "CO Reaction order": "e.g. 2",
                "O2 Reaction order": "e.g. 1",
                "Stability (h)": "e.g. 100",
                "Year": "e.g. 2021"
            },
        "Carbon dioxide hydrogenation":
            {
                "Formula": "e.g. ZnOx",
                "Type": "",
                "Elements": "e.g. Zn,O",
                "Content": "e.g. Zn/O=1/1",
                "Structural Property": "e.g. a physical mixture of ZnO (8wt%) and non-acidic SiO2 material",
                "Temperature(Celsius@conversion 10%)": "e.g. 550",
                "Temperature(Celsius)": "e.g. 550",
                "Pressure (bar)": "e.g. 1.2",
                "Reactant": "e.g. CO:O2=2:1",
                "pressure of CO2 (bar)": "e.g. 0.7",
                "pressure of H2 (bar)": "e.g. 0.5",
                "pressure of CO (bar)": "e.g. 0.2",
                "rate (g Kgcat-1 h-1)": "e.g. 1.7",
                "CH3OH selectivity (%)": "e.g. 91.9",
                "CO selectivity (%)": "e.g. 91.9",
                "CO2 Conversion (%)": "e.g. 91.9",
                "CO Conversion (%)": "e.g. 91.9",
                "particle size(nm)": "e.g. 20",
                "TOF (s-1)": "e.g. 10",
                "Apparent activation energy Ea (kJ/mol)": "e.g. 100",
                "Stability (h)": "e.g. 100",
                "CO2 Reaction order": "e.g. 2",
                "H2 Reaction order": "e.g. 1",
                "CO Reaction order": "e.g. 2",
                "CH3OH Reaction order": "e.g. 2",
                "Year": "e.g. 2024",
                "last corresponding author": "e.g. Ang Cao, Hao Li"
            },
        "Thermal Ammonia Synthesis":
            {
                "Formula": "e.g. ZnOx",
                "Elements": "e.g. Zn,O",
                "Content": "e.g. Zn/O=1/1",
                "Structural Property": "e.g. a physical mixture of ZnO (8wt%) and non-acidic SiO2 material",
                "Temperature(Celsius)": "e.g. 550",
                "total Pressure (bar)": "e.g. 1.2",
                "Reactant ratio": "e.g. CO:O2=2:1",
                "pressure of N2 (bar)": "e.g. 0.7",
                "pressure of H2 (bar)": "e.g. 0.7",
                "gas space velocity (mL/h)": "e.g. 20",
                "NH3 formation rate (g Kgcat-1 h-1)": "e.g. 27",
                "N2 Conversion (%)": "e.g. 91.9",
                "particle size(nm)": "e.g. 20",
                "TOF (s-1)": "e.g. 10",
                "Apparent activation energy Ea (kJ/mol)": "e.g. 100",
                "Stability (h)": "e.g. 100",
                "N2 Reaction order": "e.g. 2",
                "H2 Reaction order": "e.g. 1",
                "NH3 Reaction order": "e.g. 2",
                "Year": "e.g. 2024",
                "last corresponding author": "e.g. Ang Cao, Hao Li"
            },
        "CO2methonal2DMC":
            {
                "Formula": "e.g., P-CeO2-NR",
                "Elements": "e.g., Ce,O",
                "Content": "e.g., AC-Fe=0.1838:1",
                "Structural Property": "e.g., cubofluorite",
                "Dehydrating agent": "e.g., 2-CP",
                "methanol/dehydrating agent (mol/mol)": "e.g., 21.3",
                "Temperature(Celsius)": "e.g., 139.85",
                "Pressure (MPa)": "e.g., 2",
                "rate (mmol Kgcat-1 h-1)": "e.g, 11.9",
                "DMC selectivity (%)": "e.g., 100",
                "CH3OH Conversion (%)": "e.g., 5.5",
                "DMC Yield (%)": "e.g., 23.5",
                "particle size(nm)": "e.g., 11",
                "Stability (h)": "e.g., 24",
                "Year": "e.g., 2024",
                "last corresponding author": "e.g., Hao Li"
            },
        "Fischer-Tropsch Synthesis":
            {
                "Formula": "e.g., Co/Al2O3",
                "Pore size (nm)": "e.g., 8",
                "Pore volume (m3g-1)": "e.g., 0.34",
                "Elements": "e.g., Co, Al, O",
                "Content": "e.g., Co=20 wt%",
                "BET surface area (m2g-1)": "e.g., 139",
                "Dispersion (%)": "e.g., 4.4",
                "Co loading (%)": "e.g., 20",
                "Particle size (nm)": "e.g., 9.3",
                "Degree of reduction (%)": "e.g., 28.4",
                "Reduction temperature (K)": "e.g., 673",
                "Catalyst support": "e.g., Al2O3",
                "Catalyst promoter": "e.g., Ba",
                "H2/CO": "e.g., 2",
                "Temperature(K)": "e.g., 498",
                "Pressure(Mpa)": "e.g., 2",
                "Time on stream(h)": "e.g., 48",
                "GHSV(h-1)": "e.g., 1000",
                "GHSV(cm3g-1h-1)": "e.g., 1000",
                "CO conversion rate": "e.g., 58.4",
                "TOF(s-1)": "e.g., 0.0189",
                "C1 hydrocarbons selectivity (%)": "e.g., 16.1",
                "C5+hydrocarbons selectivity": "e.g., 67.6",
                "Year": "e.g., 2024"
            },
        "Methanol Oxidative to DMC":  # Methanol Oxidative Carbonylation to DMC
            {
                "Formula": "e.g. Cu-N-C",
                "Elements": "e.g., Cu, C, N, O",
                "Content": "e.g. Cu = 7.0 or Cu/C = 7/93",
                "Structural Property": "e.g. Single Cu atoms on nitrogen doped graphene",
                "Device": "e.g. Slurry bed or Fixed bed",
                "Temperature (Celsius)": "e.g. 120",
                "Time (h)": "e.g., 1.5",
                "total Pressure (bar)": "e.g., 30",
                "Mass of catalyst (mg)": "e.g., 100",
                "Volume of CH3OH (mL)": "e.g., 7.5",
                "pressure of CO (bar)": "e.g., 20",
                "pressure of O2 (bar)": "e.g., 10",
                "Volume flow rate of CH3OH (mL/min)": "e.g., 0.02",
                "Volume flow rate of CO (mL/min)": "e.g., 26",
                "Volume flow rate of O2 (mL/min)": "e.g., 2",
                "CH3OH Conversion (%)": "e.g., 3.1",
                "DMC selectivity": "e.g., 97.6",
                "CO Conversion (%)": "e.g., 14",
                "O2 Conversion (%)": "e.g., 20",
                "Space-time yield of DMC (g·gcat-1·h-1)": "e.g., 1.67",
                "Space-time yield of DMC (g·gmetal-1·h-1)": "e.g., 23.8",
                "particle size(nm)": "e.g., 7.5",
                "TOF (h-1)": "e.g., 16.8",
                "Average deactivation every 10 hours (%)": "e.g., 4.3",
                "Average deactivation per cycle (%)": "e.g., 2.5",
                "last corresponding author": "e.g., Hao Li",
                "Year": "2018"
            },
    },
    "photo": {
        # photocatalysis
        "Solar Water Splitting": {
            "Formula": "e.g., TiO2@Pt,RuO2",
            "Elements": "e.g., Ti,Pt,Ru,O",
            "Content": "e.g. Ti/Pt = 1:1",
            "Structural Property": "e.g., titanium dioxide (TiO₂) (001)face is combined with platinum (Pt) and ruthenium dioxide (RuO₂).",
            "pH": "e.g., 1.5",
            "bandgap (eV)": "e.g., 3.2",
            "absorption range (nm)": "e.g., 385",
            "Reactant": "e.g., water",
            "Light source": "e.g., 450-W Xe lamp",
            "H2 evolution rate (umol/h)": "e.g., 2.8",
            "O2 evolution rate (umol/h)": "e.g., 1.4",
            "reaction duration (h)": "e.g., 25",
            "quantum efficienty at light wavelength (%@nm)": "e.g., 30@10",
            "Apparent quantum yield at light wavelength (%@nm)": "e.g., 20@10",
            "Year": "e.g., 2024",
            "last corresponding author": "e.g., Michael Gratze",
            "Corresponding author institute": "e.g., Tohoku university"
        },
    }

}

subtype_dict = {
    "Platinum/Precious_Group_Metal": ["Pt-based", "Ru-based", "Rh-based", "Pd-based",
                                      "Os-based", "Ir-based", "Au-based", "Ag-based"],
    "Metal/Alloy": ["Transition Metal/Alloy", "Main group Metal/Alloy"],
    "Metal_C/N/O/HO/F/S/P-ides": ["Carbide", "Nitride", "Oxide", "Hydroxide",
                                  "Fluoride", "Sulfide", "Phosphide"],
    "Metal-Nitrogen-Carbon(CNT/graphene)": ["Single atom catalysts (pyridine/pyrrole-N)",
                                            "Single atom catalysts (COF/MOF)",
                                            "Single-atom catalysts with other elemental coordination",
                                            "Dual atom catalysts", "Metal/Nitrogen-doped CNT",
                                            "Metal/Nitrogen-doped graphene"],
    "2D_materials": ["graphene/graphene oxide", "MXene", "Transition metal sulphides(TMDs)", "Borophene/BN"],
    "Perovskite": [],
    "Others": []
}

type_list = [
    "Platinum/Precious_Group_Metal",
    "Metal/Alloy",
    "Metal_C/N/O/HO/F/S/P-ides",
    "Metal-Nitrogen-Carbon(CNT/graphene)",
    "2D_materials",
    "Perovskite",
    "Others"
]

# Define the dictionary with reaction names as keys
reaction_options = {
    "Carbon Dioxide Reduction": {
        "Main product": [
            'Acetate', 'Carbon monoxide(CO)', "Methanal(CH2O)", 'Formate', 'Ethylene(C2H4)',
            'Ethanol(CH3CH2OH)', 'Ethanal', 'Methanol', "Methane(CH4)", "Hydrogen(H2)",
            "Ethane (C2H6)", "C3 products"
        ],
        "Other product (FE > 10%)": [
            'Acetate', 'Carbon monoxide(CO)', "Methanal(CH2O)", 'Formate', 'Ethylene(C2H4)',
            'Ethanol(CH3CH2OH)', 'Ethanal', 'Methanol', "Methane(CH4)", "Hydrogen(H2)",
            "Ethane (C2H6)", "C3 products", "NA"
        ]
    },
    "CORR": {
        "Main product": [
            'Acetate', 'Carbon monoxide(CO)', "Methanal(CH2O)", 'Formate', 'Ethylene(C2H4)',
            'Ethanol(CH3CH2OH)', 'Ethanal', 'Methanol', "Methane(CH4)", "Hydrogen(H2)",
            "Ethane (C2H6)", "C3 products"
        ],
        "Other product (FE > 10%)": [
            'Acetate', 'Carbon monoxide(CO)', "Methanal(CH2O)", 'Formate', 'Ethylene(C2H4)',
            'Ethanol(CH3CH2OH)', 'Ethanal', 'Methanol', "Methane(CH4)", "Hydrogen(H2)",
            "Ethane (C2H6)", "C3 products", "NA"
        ]
    },
    "Ammonia Synthesis": {
        "Isotope labeling": [
            "yes", "no"
        ],
        "Reactant": [
            'N2', 'NO/NO2/NO3', "NO3-/NO2-/NO-"
        ]
    },
    "Epoxide Production": {
        "Main product": [
            'cyclooctene oxide', 'propylene oxide', "ethylene oxide", 'acrolein', 'acrylic acid',
            'allyl alcohol', 'propyiene glycol', 'acetone'
        ]
    },
    "Nitrogen Oxidation Reaction": {
        "Main product": [
            'NO3-', 'NO2-', 'NO-'
        ]
    },
    "NH3 Oxidation Reaction": {
        "Main product": [
            'N2', 'N2O'
        ]
    },
    "Urea Oxidation Reaction": {
        "Main product": [
            'N2', 'NO-', 'NO2-', 'NO3-', 'CO2', 'CO'
        ]
    }
}
